import shortid from 'shortid'
import { operatorFields } from 'features/rules'
import { 
  transactionFields as tFields
} from 'features/transactions'
import { 
  actionTypes, 
} from 'features/rules'
import * as R from 'ramda'

/**
 * @returns {string} A temporary id in the from of 'tmp_' + random
 */
const ruleTmpMakeId = () => `tmp_${shortid.generate()}`

/**
 * 
 * @param {string} tmpId An id generated by ruleTmpMakeId
 * @param {string} origDescription origDescription from active transaction
 * @param {date} date date from active transaction
 * @returns {object} A new Rule
 */
export const ruleTmpMake = (origDescription, date) => {
  const id = ruleTmpMakeId()
  return {
    _id: id,
    dirty: false,
    isTmpRule: R.startsWith('tmp_', id),
    criteria: [
      {
        _id: ruleTmpMakeId(),
        field: tFields.description.name,
        operation: operatorFields.equals.name,
        value: origDescription,
        active: true,
      },
      {
        _id: ruleTmpMakeId(),
        field: tFields.date.name,
        operation: operatorFields.equals.name,
        value: date,
        active: false
      }
    ],
    actions: [
      {
        _id: ruleTmpMakeId(),
        actionType: actionTypes.replaceAll.name,
        field: tFields.description.name,
        replaceWithValue: origDescription
      },
      {
        _id: ruleTmpMakeId(),
        actionType: actionTypes.categorize.name,
        category1: '',
        category2: '',
      }
    ],
  }
}